# Generated by Django 4.1.5 on 2023-02-26 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                ("ages", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=150)),
                ("subCategories", models.TextField()),
                ("openhours", models.TextField()),
                ("address", models.CharField(max_length=100)),
                ("other_info", models.TextField()),
                (
                    "locid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
