# Generated by Django 4.1.5 on 2023-02-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_location_locid_location_lat_location_lon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(
                decimal_places=6, default=-20.212392, max_digits=100
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="lon",
            field=models.DecimalField(
                decimal_places=6, default=20.212121, max_digits=100
            ),
        ),
    ]
