# Generated by Django 4.1.5 on 2023-02-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_location_lat_alter_location_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(
                decimal_places=6, default=25.750156, max_digits=100
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="lon",
            field=models.DecimalField(
                decimal_places=6, default=-80.27964, max_digits=100
            ),
        ),
    ]
